# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Song Notes! Easy-to-follow guitar lessons, all hand-made by @davidpots
email: davidpots@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Easy to follow video guitar lessons, all hand-crafted by David Pots. In the 150+ available lessons, I'll show you the tabs, chords, fingerpicking technique, and other tips you'll need to learn your favorite songs on guitar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima // Disabled because I don't want no gem-based theme (DP May 28, 2017)
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  songs:
    output: true
    permalink: /:collection/:name/
  practice:
    output: true
    permalink: /:collection/:slug/
  warmup:
    output: true
    permalink: /:collection/:slug/
  tips:
    output: true
    permalink: /:collection/:slug/
