# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Song Notes // Library of video guitar lessons and PDF chord sheets, all hand-made by David Pots.
email: davidpots@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Easy-to-follow video guitar lessons and PDF chord sheets, all hand-crafted by David Pots. Learn the chord shapes, progressions, strumming patterns, and lyrics to help you learn your favorite guitar songs -- with tabs included.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima // Disabled because I don't want no gem-based theme (DP May 28, 2017)
plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  courses:
    output: true
  course_lessons:
    output: true
  topics:
    output: true
  lessons:
    output: true
    permalink: /:collection/:slug/
  songs:
    output: true
    permalink: /:collection/:name/
  warmup:
    output: true
    permalink: /:collection/:slug/
  tips:
    output: true
    permalink: /:collection/:slug/
  misc:
    output: true
    permalink: /lessons/:slug/

defaults:
  - scope:
      path: ""
      type: "course_lessons"
    values:
      layout: "course_lesson"
